### ISSUE TITLE
KO Clean Kerning Groups does not work on glyphspackage files

### ISSUE THREAD

**Issue by schriftlabor-miriam** [eweracs/glyphs-scripts#11]

**Comment by eweracs** [comment]
This needs to be used on .glyphs files only, sorry. Haven't updated it for .glyphspackage files yet.

In the meantime, in your text editor of choice (tested in Sublime): Open the .glyphspackage directory and search for every occurence of "KO_" and delete it. This is essentially what the script does anyway.

**Comment by eweracs** [comment]
Tamir fixed this in deec170df2822b0d649ad3be90305eda9620cf3d. Thanks!
