### ISSUE TITLE
Consider using the “Axis Location” custom parameter for “Make Web Weights”

### ISSUE THREAD

**Issue by florianpircher** [eweracs/glyphs-scripts#5]
That way, the internal master axes coordinates can stay as they are and only the exported (external) coordinates are changed.

<img width="625" alt src="https://user-images.githubusercontent.com/3776198/143311903-82c249ab-c58e-4f06-ac61-316b3de16e5c.png">

**Comment by eweracs** [comment]
This issue was resolved in d8fcd2eb52905a3f7447f34664ab70e41a0a1f49 by deleting the script.
