### ISSUE TITLE
Interpolation Preview

### ISSUE THREAD

**Issue by hadddid** [eweracs/glyphs-scripts#7]
Heres the error code when I run the code:

Traceback (most recent call last):
  File "<macro panel>", line 280
  File "<macro panel>", line 84, in __init__
IndexError: list index out of range
<img width="1440" alt="Screen Shot 2021-12-13 at 18 35 22" src="https://user-images.githubusercontent.com/90374469/145809403-9829b8a4-e77d-4b78-94bc-8aef82f98a4c.png">

**Comment by eweracs** [comment]
I cannot reproduce this issue. Can it be that you have an axis in your font with only one coordinate? The script requires all axes to have at least two coordinates per axis. How many axes do you have and what are their masters coordinates?

**Comment by eweracs** [comment]
I added a check with an error description based on what I assume the issue to be. Please use the new script (and check your file). Thanks!

**Comment by hadddid** [comment]
My bad, having italic axes with empty value. Thank You!
