### ISSUE TITLE
HT Letterspacer - STOPED

### ISSUE THREAD

**Issue by etunni** [eweracs/glyphs-scripts#8]
Hi,
This is the message at macro window G3 latrest cutting edge.

File “Visualiser.py”, line 9
** import preview as preview**
ModuleNotFoundError: No module named 'preview’
Traceback (most recent call last):

Great work!
Thanks

**Comment by eweracs** [comment]
Thank you. Yes, I am aware of this issue and am trying to reach @mark2mark about this import, I think he wrote it ;)
Mark, check your Instagram DMs!

**Comment by Mark2Mark** [comment]
Hi there, I’ll have a look.

@eweracs my instagram is not a messaging tool for me, I barely check it (not to mention preventing notifications from it). Github is perfectly fine for such things :)

**Comment by Mark2Mark** [comment]
This doesn’t look like I have added this?!

<img width="927" alt="Screenshot 2022-03-03 at 08 16 24" src="https://user-images.githubusercontent.com/5824595/156515422-d3f2637d-3e86-4488-b77e-1a7b2c4cdd99.png">
<img width="600" alt="Screenshot 2022-03-03 at 08 18 00" src="https://user-images.githubusercontent.com/5824595/156515561-965bd7fd-3ca8-4059-98e6-9cee3bedd83a.png">

**Comment by Mark2Mark** [comment]
The preview from Kernkraft is written by me and very custom to Kernkraft, but not the import in Letterspacer.
You could go for any of [those views from the Glyphs SDK](https://github.com/schriftgestalt/GlyphsSDK/tree/Glyphs3/ObjectWrapper/GlyphsApp/UI) here, those are closest to the API, should work well with G3 and are easier for you to customize to your needs.

**Comment by eweracs** [comment]
Hi Mark, thanks a lot for your response! What I meant was that the module I was trying to import was written by you. I shall see what I can do to rebuild a similar functionality custom to my needs.

@etunni what you can do as a temporary workaround is to install the Kernkraft plugin, it includes the module I use in my script (and is a brilliant tool in itself as well!). I will try and update this as soon as possible. Sorry for the inconvenience!

**Comment by etunni** [comment]
Hi guys, I hope are you fine.
I installed Kerncraft and solved the issue, thanks @Mark2Mark and @eweracs
Have a great day!

**Comment by Mark2Mark** [comment]
@etunni, please be aware that this is jsut a temporary workaround. It only fixes, that the imported module is available to this script here. However, that imported module is not written to be used as a module, so it causes dependencies to all other scripts using it. Whenever I change something in my "preview" code, it can break any other script using it.

Have a great day, both of  you too :)

**Comment by etunni** [comment]
@Mark2Mark thanks for the advice.
Keep up your great works!

**Comment by eweracs** [comment]
Hello, this issue is now properly fixed. I didn't know about GlyphView and that it is provided by Glyphs itself. Thanks nonetheless to Mark for your feedback! I will study your code more to see how I can customise GlyphView if I need to.
